### ISSUE TITLE
BUILDING gives X11-only instructions

### ISSUE THREAD

**Issue by nilsbecker** [nojb/llpp#1]
i'm opening this to switch over from email (thanks for the reply)
i'm now using 
```
make force_mupdf
make
```
this indeed gives an executable `llpp` which seems to work!

**Comment by nojb** [comment]
Great!  Don't hesitate to report any issues you find.  Note that trackpad scrolling is still a little clunky, I am hoping to improve this soon ...

**Comment by nojb** [comment]
The build system is going to change before integrating this upstream, so closing this now.
