### ISSUE TITLE
Can't rebind anything with Shift key

### ISSUE THREAD

**Issue by freed00m** [nojb/llpp#10]
Simply,

I have no idea if this is even implemented cause none of the examples in Arch wiki or source code mention something about how to bind Shift.

Using Manjaro linux ( Arch based distro ).

I've tried these and without any effect
```
            <map in='Shift+b' out=''/>
            <map in='Shift+B' out=''/>
            <map in='shift-b' out=''/>
            <map in='B' out=''/>
            <map in='<s-b>' out=''/>
```

So if implemented, I ask for How to ( i will attempt then update the wiki )
If not implemented then I would like to humbly ask for implementation :+1:

**Comment by moosotc** [comment]
Antonín Dach <notifications@github.com> writes:

> Simply,
>
> I have no idea if this is even implemented cause none of the examples
> in Arch wiki or source code mention something about how to bind Shift.
>
> Using Manjaro linux ( Arch based distro ).
>
> I've tried these and without any effect
> ```
>             <map in='Shift+b' out=''/>
>             <map in='Shift+B' out=''/>
>             <map in='shift-b' out=''/>
>             <map in='B' out=''/>
>             <map in='<s-b>' out=''/>
> ```
>
> So if implemented, I ask for How to ( i will attempt then update the wiki )
> If not implemented then I would like to humbly ask for implementation :+1: 


Thing is in X11 pressing 'b' sends (well...) 'b' and 'B' sends 'B' how
modifiers fall into the picture i haven't checked, but will do.. Easiest
is probably to just see what xev(1) says... Maybe tomorrow...

-- 
mailto:moosotc@gmail.com

**Comment by freed00m** [comment]
@moosotc -

Well, xev is repporting "B" as you said, this is a sample when pressing "Shift-B".

```
KeyPress event, serial 33, synthetic NO, window 0x2c00001,
    root 0x6bf, subw 0x0, time 51441204, (286,6), root:(1197,542),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x2c00001,
    root 0x6bf, subw 0x0, time 51441308, (286,6), root:(1197,542),
    state 0x1, keycode 56 (keysym 0x42, B), same_screen YES,
    XLookupString gives 1 bytes: (42) "B"
    XmbLookupString gives 1 bytes: (42) "B"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x2c00001,
    root 0x6bf, subw 0x0, time 51441372, (286,6), root:(1197,542),
    state 0x1, keycode 56 (keysym 0x42, B), same_screen YES,
    XLookupString gives 1 bytes: (42) "B"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x2c00001,
    root 0x6bf, subw 0x0, time 51441492, (286,6), root:(1197,542),
    state 0x1, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

That's why it might be a bug, I am able to rebind shift in vim like family (qutebrowser, ranger, vim, ... ) and I struggle here.

**Comment by freed00m** [comment]
@moosotc YES! that works, :+1: I should have tried every permutation, but you must admit it's not that straight forward as shift-b doesn't work.

**Comment by moosotc** [comment]
Antonín Dach <notifications@github.com> writes:

> @moosotc YES! that works, :+1: I should have tried every permutation,
> but you must admit it's not that straight forward as shift-b doesn't
> work.

That's what X11 reports, a code that represents upper-case B and a
modifier that represents shift, not much i can do about it.

-- 
mailto:moosotc@gmail.com

**Comment by freed00m** [comment]
Ok, I thought other programs apply lowercase for keys like ctrl shift and so on so on.

Again thank you, I don't mind being this as wontfix, maybe a small mention in you website or readme about key config might help..

I am closing this ;)

**Comment by moosotc** [comment]
Antonín Dach <notifications@github.com> writes:

> Ok, I thought other programs apply lowercase for keys like ctrl shift
> and so on so on.
>
> Again thank you, I don't mind being this as wontfix, maybe a small
> mention in you website or readme about key config might help..
>

I'm not a website (last time i checked at least), putting some soft of
caveat emptor note in the docs is probably warranted, thanks, will think
were to put it.

> I am closing this ;) 

Thanks :)

-- 
mailto:moosotc@gmail.com
