### ISSUE TITLE
. does not work

### ISSUE THREAD

**Issue by nojb** [nojb/llpp#8]

**Comment by moosotc** [comment]
When pressing '.' here keyDown receives key=0x2e and this gets translated into KPdelete inside wsi_cocoa.ml

**Comment by moosotc** [comment]
USB keyboard does indeed produce 0x2e when kpdelete is pressed... So color me confused... As does '.' on the AIR built-in keyboard.

**Comment by moosotc** [comment]
keypad delete has a '.' above delete, and AIR for whatever reason:
a) ignores num lock
b) acts as if num lock is always activated (even though the led is not lit)
So mystery solved:
a) KPdelete in wsi_cocoa.ml is wrong (just removing it solves the original issue)
b) I do not understand how cocoa deals with numlock

**Comment by nojb** [comment]
Good detective work!  I was travelling so am just seeing this now.  I will try to figure out numlock.  Thanks!

**Comment by moosotc** [comment]
Nicolas Ojeda Bar <notifications@github.com> writes:

> Good detective work!  I was travelling so am just seeing this now.  I
> will try to figure out numlock.  Thanks!

I believe it's a system wide issue (even _the led_ doesn't work) so
trying to solve it will likely to be a fruitless endeavor, that said
perhaps spending 10-20 minutes wouldn't hurt.

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
fwiw, '.' on the keyboard works for me

**Comment by nojb** [comment]
Seems to be fixed now, so closing.
